# ci.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set Google Cloud project
        run: gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/my-django-app:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/my-django-app:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-django-app \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/my-django-app:latest \
            --platform managed \
            --region us-central1
